CREATE TABLE USUARIOS(
CORREO VARCHAR(30) PRIMARY KEY NOT NULL,
ESTADO BOOLEAN NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
NOMBRE_USUARIO VARCHAR(20) UNIQUE NOT NULL,
CLAVE VARCHAR(20) NOT NULL,
ROL VARCHAR(15) NOT NULL,
AREA VARCHAR(20)
);
CREATE TABLE INICIATIVAS(
ID_INICIATIVAS INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(45) NOT NULL,
FECHA DATE NOT NULL,
PROPONENTES_USUARIOS_CORREO VARCHAR(35) NOT NULL,
ESTADO VARCHAR(21) NOT NULL,
CONSTRAINT INICIATIVAS_FK FOREIGN KEY (PROPONENTES_USUARIOS_CORREO)
REFERENCES USUARIOS (CORREO) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE PALABRAS_CLAVE(
PALABRA VARCHAR(15) NOT NULL,
INICIATIVAS_ID_INICIATIVAS INT NOT NULL,
PRIMARY KEY(PALABRA,INICIATIVAS_ID_INICIATIVAS),
CONSTRAINT PALABRAS_CLAVE_FK FOREIGN KEY (INICIATIVAS_ID_INICIATIVAS)
REFERENCES INICIATIVAS (ID_INICIATIVAS) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE OBSERVACIONES(
USUARIOS_DE_CONSULTA_USUARIOS_CORREO VARCHAR(35) NOT NULL,
INICIATIVAS_ID_INICIATIVAS INT NOT NULL,
COMENTARIO VARCHAR(500),
ME_GUSTA BOOLEAN,
INTERES VARCHAR(10),
PRIMARY KEY(USUARIOS_DE_CONSULTA_USUARIOS_CORREO,INICIATIVAS_ID_INICIATIVAS),
CONSTRAINT OBSERVACIONES_FK_USUARIOS_DE_CONSULTA FOREIGN KEY (USUARIOS_DE_CONSULTA_USUARIOS_CORREO)
REFERENCES USUARIOS (CORREO) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT OBSERVACIONES_FK_INICIATIVAS FOREIGN KEY (INICIATIVAS_ID_INICIATIVAS)
REFERENCES INICIATIVAS (ID_INICIATIVAS) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
);

