CREATE TABLE USUARIOS(
CORREO VARCHAR(30) PRIMARY KEY NOT NULL,
ESTADO BOOLEAN NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
NOMBRE_USUARIO VARCHAR(20) UNIQUE NOT NULL,
CLAVE VARCHAR(20) NOT NULL,
ROL VARCHAR(15) NOT NULL,
AREA VARCHAR(20)
);
CREATE TABLE INICIATIVAS(
ID_INICIATIVAS INT PRIMARY KEY NOT NULL,
DESCRIPCION VARCHAR(45) NOT NULL,
FECHA DATE NOT NULL,
PROPONENTES_USUARIOS_CORREO VARCHAR(35) NOT NULL,
ESTADO VARCHAR(21) NOT NULL,
CONSTRAINT INICIATIVAS_FK FOREIGN KEY (PROPONENTES_USUARIOS_CORREO)
REFERENCES USUARIOS (CORREO) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE COMENTARIOS(
IDF_INICIATIVA INT NOT NULL,
IDF_USUARIO VARCHAR(35) NOT NULL,
COMENTARIO BOOLEAN,
PRIMARY KEY(IDF_INICIATIVA,IDF_USUARIO),
CONSTRAINT COMENT_FK_INI  FOREIGN KEY (IDF_INICIATIVA)
REFERENCES INICIATIVAS (ID_INICIATIVAS) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT COMENT_FK_US  FOREIGN KEY (IDF_USUARIO)
REFERENCES USUARIOS (CORREO) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
);
CREATE TABLE LIKES(
IDF_INICIATIVA INT NOT NULL,
IDF_USUARIO VARCHAR(35) NOT NULL,
BOOLLIKE BOOLEAN,
PRIMARY KEY(IDF_INICIATIVA,IDF_USUARIO),
CONSTRAINT LIKES_FK_INI  FOREIGN KEY (IDF_INICIATIVA)
REFERENCES INICIATIVAS (ID_INICIATIVAS) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT LIKES_FK_US  FOREIGN KEY (IDF_USUARIO)
REFERENCES USUARIOS (CORREO) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION
);

