CREATE TABLE USUARIOS(
CORREO VARCHAR(30) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR(20) NOT NULL,
APELLIDO VARCHAR(20) NOT NULL,
NOMBRE_USUARIO VARCHAR(20) UNIQUE NOT NULL,
CLAVE VARCHAR(20) NOT NULL,
ROL VARCHAR(15) NOT NULL
);